name: Update Dist Branch

on:
  push:
    branches:
      - dev

jobs:
  update-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'PetrCala'
          git config --global user.email 'cala.p@seznam.cz'

      - name: Run Update Script
        run: |
          git checkout dev
          chmod +x ./update_all.sh
          ./update_all.sh

      - name: Update Dist Branch
        run: |
          git subtree split --prefix=Dist --branch temporary_branch
          git checkout -- Dist
          git merge temporary_branch --allow-unrelated-histories -Xtheirs --no-edit
          git push origin -- Dist
          git branch -D temporary_branch
